include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  errors:
    unawaited_futures: error
    unrelated_type_equality_checks: error
    tighten_type_of_initializing_formals: error
    discarded_futures: error  # Don't invoke asynchronous functions in non-async blocks.

linter:
  rules:
    unnecessary_this: false
    constant_identifier_names: false
    avoid_print: false
    unawaited_futures: true
    unnecessary_await_in_return: true

    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_parameters: true
    prefer_final_in_for_each: true

    always_declare_return_types: true
    unrelated_type_equality_checks: true
    tighten_type_of_initializing_formals: true
    unnecessary_lambdas: true
    use_decorated_box: true
    use_colored_box: true
