name: ghcp
description: GitHub file downloader tool.
version: 0.1.3

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1
  uuid: ^3.0.6
  archive: ^3.3.1

dependencies:
  args: ^2.3.1
  crypto: ^3.0.2
  either_dart: ^0.2.0
  path: ^1.8.2
