# ! THIS JOB EXPOSES GITHUB TOKENS TO THE TEST
# ! IT SHOULD NOT BE RUN ON PULL REQUESTS

name: unittest

on:
  push:
    branches: [dev]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

jobs:
  test:

    timeout-minutes: 9
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.18.0]
        platform: [vm]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Tests
        run: dart test --platform ${{ matrix.platform }} --timeout=60s
        env:
          # we use gh, so we need the token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  to-staging:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}