# ! THIS JOB EXPOSES GITHUB TOKENS TO THE TEST
# ! IT SHOULD NOT BE RUN ON PULL REQUESTS

name: unittest

on:
  push:
    branches: [dev]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

jobs:
  build:

    timeout-minutes: 9
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.0

      - name: Install dependencies
        run: dart pub get

      - name: Update constants
        run: dart script/patch_version.dart

      - name: Tests
        run: dart test --platform vm --timeout=60s
        env:
          # we use gh, so we need the token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build executable
        run: |
          mkdir build
          dart compile exe bin/ghcp.dart -o build/ghcp.exe

      - name: Archive executables
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: build/ghcp.exe


  to-staging:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}